public class EnumUser {
    enum MenuOptionsUser {
        VISUALIZZA_TUTTI_PRODOTTI,
        RICERCA_PER_TIPO_DISPOSITIVO,
        RICERCA_PER_PRODUTTORE,
        RICERCA_PER_MODELLO,
        RICERCA_PER_PREZZO_DI_VENDITA,
        RICERCA_PER_RANGE_DI_VENDITA,
        AGGIUNGI_AL_CARRELLO,
        RIMUOVI_DAL_CARRELLO,
        CALCOLARE_IL_TOTALE,
        VISUALIZZA_IL_CARRELLO,
        ACQUISTA,
        FINE;

    }
}
