 enum MenuOptionsOperator {
        VISUALIZZA_TUTTI_PRODOTTI,
        RICERCA_PER_TIPO_DISPOSITIVO,
        RICERCA_PER_PRODUTTORE,
        RICERCA_PER_MODELLO,
        RICERCA_PER_PREZZO_DI_VENDITA,
        RICERCA_PER_PREZZO_DI_ACQUISTO,
        RICERCA_PER_RANGE_DI_ACQUISTO,
        RICERCA_SPESA_MEDIA_DISPOSITIVO,
        AGGIUNGI_DISPOSITIVO_AL_MAGAZZINO,
        RIMUOVI_DISPOSITIVO_DAL_MAGAZZINO,
        FINE,
        UNKNOWN
    }

